#!/bin/sh

BATTERY="$(acpi | awk -F ' ' 'END {print $4}' | tr -d \%,)"
CHARGE="$(acpi | awk -F ' ' 'END {print $3}' | tr -d \,)"

BASE_ICON_PATH="/usr/share/icons/Papirus-Dark/24x24@2x/panel/"

get_icon() {
  BATTERY_LEVEL=$((BATTERY / 10 * 10))
  if [ "$CHARGE" = "Charging" ]; then
    ICON_NAME="battery-$(printf "%03d" $BATTERY_LEVEL)-charging.svg"
  else
    ICON_NAME="battery-$(printf "%03d" $BATTERY_LEVEL).svg"
  fi
  echo "${BASE_ICON_PATH}${ICON_NAME}"
}

if [[ $1 == '--icon' ]]; then
  get_icon
else
  echo "${BATTERY}%"
fi
