#!/bin/sh

# Get the connection status for Ethernet and Wi-Fi
WIFI_STATUS=$(nmcli -t -f TYPE,STATE dev | grep '^wifi:' | cut -d: -f2)
ETHERNET_STATUS=$(nmcli -t -f TYPE,STATE dev | grep '^ethernet:' | cut -d: -f2)

# Get Wi-Fi signal strength if Wi-Fi is connected
if [ "$WIFI_STATUS" = "connected" ]; then
  SIGNAL_STRENGTH=$(nmcli -t -f active,ssid,signal dev wifi | grep '^yes' | cut -d':' -f3)
  WIFI_NETWORK=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d':' -f2)
fi

BASE_ICON_PATH="/usr/share/icons/Papirus-Dark/24x24@2x/panel/"

get_icon() {
  if [ "$ETHERNET_STATUS" = "connected" ]; then
    ICON_NAME="network-wired-connected.svg"
  elif [ "$WIFI_STATUS" = "connected" ]; then
    SIGNAL_LEVEL=$((SIGNAL_STRENGTH / 20 * 20))
    ICON_NAME="network-wireless-${SIGNAL_LEVEL}.svg"
  else
    ICON_NAME="network-wired-disconnected.svg"
  fi
  echo "${BASE_ICON_PATH}${ICON_NAME}"
}

if [ "$1" = "--icon" ]; then
  get_icon
else
  if [ "$ETHERNET_STATUS" = "connected" ]; then
    echo "Wired"
  elif [ "$WIFI_STATUS" = "connected" ]; then
    echo "$WIFI_NETWORK"
  else
    echo "No connection"
  fi
fi

